kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-app-set
  namespace: xdzhang-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-set
  template:
    metadata:
      labels:
        app: app-set
    spec:
      containers:
        - name: container
          image: registry.alauda.cn:60080/ait/nginx-unprivileged:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: abc
              value: '123'
          imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
