kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app-set-router-1
  namespace: xdzhang-project
spec:
  host: app-set-router-1-xdzhang-project.apps.ocpa.alaudatech.net
  to:
    kind: Service
    name: app-set
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
